# Generated by Django 4.1.2 on 2022-11-24 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('symbol', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('acronym', models.CharField(max_length=25)),
                ('market_id', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('country_code', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=25)),
                ('abbr', models.CharField(max_length=10)),
                ('abbr_dst', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(max_length=150)),
                ('symbol', models.CharField(max_length=10)),
                ('has_intraday', models.BooleanField()),
                ('has_eod', models.BooleanField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='Intraday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('acronym', models.CharField(max_length=25)),
                ('market_id', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('country_code', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('datetime', models.DateTimeField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.ticker')),
            ],
        ),
        migrations.AddField(
            model_name='exchange',
            name='timezone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.timezone'),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('bg_color', models.CharField(max_length=25)),
                ('curve_color', models.CharField(max_length=25)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.ticker')),
            ],
        ),
    ]
