# Generated by Django 4.1.2 on 2022-11-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='ticker',
        ),
        migrations.AddField(
            model_name='chart',
            name='file_format',
            field=models.CharField(default='.png', max_length=5),
            preserve_default=False,
        ),
    ]
