# Generated by Django 4.1.2 on 2022-11-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_remove_chart_end_date_remove_chart_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='name',
            new_name='chart_type',
        ),
    ]
