# Generated by Django 4.1.2 on 2022-11-24 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charts', '0003_rename_name_chart_chart_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_month_api_calls_limit', models.BooleanField()),
                ('month_api_calls_limit', models.SmallIntegerField()),
                ('month_api_calls_counter', models.SmallIntegerField()),
                ('has_saved_charts_limit', models.BooleanField()),
                ('saved_charts_limit', models.SmallIntegerField()),
                ('saved_charts_counter', models.SmallIntegerField()),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
